runtime: nodejs16
handlers: 
  #serve with all static file urls ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
